<html>
<head>
    <title>${title}</title>
</head>
<body>
<div>
    <h1>${title}</h1>
	<p>
	  Enter any URL w/in the context of this application that matches:
	</p>
	  <ul>
	    <li>/matchdict</li>
		<ul>
          <li><b>/matchdict/{foo}</b></li>
          <li><b>/matchdict/{foo}/{bar}</b></li>
          <li><b>/matchdict/{foo}/{bar}/{baz}</b></li>
		</ul>
		<li>/factory</li>
		<ul>
          <li><b>/factory/{foo}</b></li>
          <li><b>/factory/{foo}/{bar}</b></li>
          <li><b>/factory/{foo}/{bar}/{baz}</b></li>
		</ul>
	  </ul>
</div>
</body>
</html>
